In [ ]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_derivative(x):
    return x * (1 - x)
def checkError(predicted_output):
    expected_output = np.array([[0], [1], [1], [0]])
    for i, j in zip(expected_output, predicted_output):
        if abs(i[0] - j[0]) > 0.001:
            return True
    return False
inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
expected_output = np.array([
    [0],
    [1],
    [1],
    [0]
])
lr = 0.1
epoch = 0
inputLayerNeurons = int(input("Enter number of input layer neurons: "))
hiddenLayerNeurons = int(input("Enter number of hidden layer neurons: "))
outputLayerNeurons = int(input("Enter number of output layer neurons: "))
hidden_weights = []
print("\nEnter weights from Input Layer to Hidden Layer:")
for i in range(inputLayerNeurons):
    hidden_weights_ind = []
    for j in range(hiddenLayerNeurons):
        weight = float(input(
            "Enter w" + str(i + 1) + str(j + inputLayerNeurons + 1) + ": "
        ))
        hidden_weights_ind.append(weight)
    hidden_weights.append(hidden_weights_ind)
output_weights = []
print("\nEnter weights from Hidden Layer to Output Layer:")
for i in range(hiddenLayerNeurons):
    output_weights_ind = []
    for j in range(outputLayerNeurons):
        weight = float(input(
            "Enter output weight: "
        ))
        output_weights_ind.append(weight)
    output_weights.append(output_weights_ind)
hidden_bias = []
output_bias = []
print("\nEnter Hidden Layer Biases:")
for i in range(hiddenLayerNeurons):
    bias = float(input("Enter hidden bias " + str(i + 1) + ": "))
    hidden_bias.append(bias)
print("\nEnter Output Layer Biases:")
for i in range(outputLayerNeurons):
    bias = float(input("Enter output bias " + str(i + 1) + ": "))
    output_bias.append(bias)
hidden_weights = np.asarray(hidden_weights)
hidden_bias = np.asarray([hidden_bias])
output_weights = np.asarray(output_weights)
output_bias = np.asarray([output_bias])
print("\nInitial Hidden Weights:")
print(hidden_weights)
print("\nInitial Hidden Bias:")
print(hidden_bias)
print("\nInitial Output Weights:")
print(output_weights)
print("\nInitial Output Bias:")
print(output_bias)
predicted_output = np.array([
    [0],
    [0],
    [0],
    [0]
])
while checkError(predicted_output):
    epoch += 1
    hidden_layer_activation = np.dot(
        inputs, hidden_weights
    )
    hidden_layer_activation += hidden_bias
    hidden_layer_output = sigmoid(
        hidden_layer_activation
    )
    output_layer_activation = np.dot(
        hidden_layer_output,
        output_weights
    )
    output_layer_activation += output_bias
    predicted_output = sigmoid(
        output_layer_activation
    )
    error = expected_output - predicted_output
    d_predicted_output = (
        error *
        sigmoid_derivative(predicted_output)
    )
    error_hidden_layer = np.dot(
        d_predicted_output,
        output_weights.T
    )
    d_hidden_layer = (
        error_hidden_layer *
        sigmoid_derivative(hidden_layer_output)
    )
    output_weights += (
        np.dot(
            hidden_layer_output.T,
            d_predicted_output
        ) * lr
    )
    output_bias += (
        np.sum(
            d_predicted_output,
            axis=0,
            keepdims=True
        ) * lr
    )
    hidden_weights += (
        np.dot(
            inputs.T,
            d_hidden_layer
        ) * lr
    )
    hidden_bias += (
        np.sum(
            d_hidden_layer,
            axis=0,
            keepdims=True
        ) * lr
    )
print("\nFinal Hidden Weights:")
print(hidden_weights)
print("\nFinal Hidden Bias:")
print(hidden_bias)
print("\nFinal Output Weights:")
print(output_weights)
print("\nFinal Output Bias:")
print(output_bias)
print("\nOutput from Neural Network:")
print(predicted_output)
print("\nBinary Output:")
print((predicted_output >= 0.5).astype(int))
print("\nNumber of Epochs:")
print(epoch)

Enter number of input layer neurons:  2
Enter number of hidden layer neurons:  2
Enter number of output layer neurons:  1



Enter weights from Input Layer to Hidden Layer:


Enter w13:  0.5
Enter w14:  0.5
Enter w23:  0.5
Enter w24:  0.5



Enter weights from Hidden Layer to Output Layer:


Enter output weight:  0.5
Enter output weight:  0.5



Enter Hidden Layer Biases:


Enter hidden bias 1:  0.1
Enter hidden bias 2:  0.1



Enter Output Layer Biases:


Enter output bias 1:  0.1



Initial Hidden Weights:
[[0.5 0.5]
 [0.5 0.5]]

Initial Hidden Bias:
[[0.1 0.1]]

Initial Output Weights:
[[0.5]
 [0.5]]

Initial Output Bias:
[[0.1]]
