In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
data = {
    'CGPA': [9.2, 8.0, 8.5, 6.0, 6.5, 8.2, 5.8, 8.9],
    'Assessment': [85, 80, 81, 45, 50, 72, 38, 91],
    'Project': [8, 7, 8, 5, 4, 7, 5, 9],
    'Result': ['Pass', 'Pass', 'Pass', 'Fail',
               'Fail', 'Pass', 'Fail', 'Pass']
}
dataset = pd.DataFrame(data)
dataset.to_csv("knearest_csv.csv", index=False)
dataset = pd.read_csv("knearest_csv.csv")
print("Shape of Dataset:")
print(dataset.shape)
print("\nFirst 5 Records:")
print(dataset.head())
print("\nLast 2 Records:")
print(dataset.tail(2))
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
print("\nInput Data (X):")
print(X)
print("\nOutput Data (y):")
print(y)
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=0
)
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("\nActual Values:")
print(y_test)
print("\nPredicted Values:")
print(y_pred)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
new_student = [[9.1, 85, 8]]
new_student_scaled = scaler.transform(new_student)
predicted = classifier.predict(new_student_scaled)
print("\nNew Student:")
print(new_student)
print("\nPredicted Result:")
print(predicted)

Shape of Dataset:
(8, 4)

First 5 Records:
   CGPA  Assessment  Project Result
0   9.2          85        8   Pass
1   8.0          80        7   Pass
2   8.5          81        8   Pass
3   6.0          45        5   Fail
4   6.5          50        4   Fail

Last 2 Records:
   CGPA  Assessment  Project Result
6   5.8          38        5   Fail
7   8.9          91        9   Pass

Input Data (X):
[[ 9.2 85.   8. ]
 [ 8.  80.   7. ]
 [ 8.5 81.   8. ]
 [ 6.  45.   5. ]
 [ 6.5 50.   4. ]
 [ 8.2 72.   7. ]
 [ 5.8 38.   5. ]
 [ 8.9 91.   9. ]]

Output Data (y):
['Pass' 'Pass' 'Pass' 'Fail' 'Fail' 'Pass' 'Fail' 'Pass']

Actual Values:
['Fail' 'Pass']

Predicted Values:
['Fail' 'Pass']

Confusion Matrix:
[[1 0]
 [0 1]]

Classification Report:
              precision    recall  f1-score   support

        Fail       1.00      1.00      1.00         1
        Pass       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00  

In [5]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
iris = load_iris()
X = iris.data
y = iris.target
target_names = iris.target_names
y_names = np.array([target_names[i] for i in y])
print("Shape of dataset:")
print(X.shape)
print("\nFirst 5 records:")
print(X[:5])
print("\nLast 2 records:")
print(X[-2:])
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_names,
    test_size=0.20,
    random_state=42
)
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
accuracy = accuracy_score(y_test, y_pred) * 100
print("Accuracy of our model is equal "
      + str(round(accuracy, 2)) + " %.")

Shape of dataset:
(150, 4)

First 5 records:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Last 2 records:
[[6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy of our model is equal 100.0 %.
